name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@1.70.0

      - uses: Swatinem/rust-cache@v2

      - name: Run cargo build
        run: cargo build

      - name: Run cargo test
        run: cargo test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@1.70.0
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Check with rustfmt
        run: cargo fmt --all -- --check

      - name: lint
        run: cargo clippy --all-targets --all-features -- --D warnings
